apiVersion: v1
kind: Service
metadata:
  name: nfs-service
spec:
  selector:
    app: nfs-webmin
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
    - name: rpcbind
      port: 111
      targetPort: 111
  type: NodePort   # Для удобного теста на minikube/kind/standalone
